name: cicd

on:
  push:

jobs:
    ci:
      name: Continuous Integration
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            flutter-version: '3.32'
            cache: true