name: cicd

on:
  push:

env:
  PATH_TO_APP : awesome_app

jobs:
    ci:
      name: Continuous Integration
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            flutter-version: '3.32'
            cache: true

        - name: Setup Pages
          id: pages
          uses: actions/configure-pages@v5

        - name: Install dependencies
          run: flutter pub get
          working-directory: ${{ env.PATH_TO_APP }}
        - name: Build app for web
          run: flutter build web --base-href "${{ steps.pages.outputs.base_path }}/"
          working-directory: ${{ env.PATH_TO_APP }}

        - name: Run tests
          run: flutter test
          working-directory: ${{ env.PATH_TO_APP }}

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: ${{ env.PATH_TO_APP }}/build/web

    cd:
      name: Continuous Deployment
      needs: ci
      runs-on: ubuntu-latest
      permissions:
        pages: write
        id-token: write